services:
  anime:
    build:
        context: .
        additional_contexts:
            nuufetch: ../../nuufetch/nuufetch
            module_anime_other: ../../nuufetch/nuuwatch-files/src/modules/anime/other
    container_name: nuuwatch
    ports:
      - "8080:3001"
    volumes:
        - ./data:/app/data
    environment:
      - RUST_LOG=info
    restart: unless-stopped
