services:
  anime:
    build:
        context: .
        additional_contexts:
            nuufetch: ../../nuufetch/nuufetch
            module_anime_other: ../../nuufetch/nuuwatch-files/src/modules/anime/other
    container_name: nuuwatch
    ports:
      - "8080:3001"
    volumes:
        - ./data:/app/data
    environment:
      - RUST_LOG=info
      - NUUWATCH_PROJECT_ROOT=/app/
      - NUUCAST_API_URL=${NUUCAST_API_URL:-http://localhost:80}
      - NUUWATCH_API_URL=${NUUWATCH_API_URL:-http://localhost:8080}
    restart: unless-stopped
